"""Schemas Pydantic do Cloud (v2.1)."""

from cloud.schemas.auth import (
    LoginRequest,
    LoginResponse,
    MovimentacaoIn,
    MovimentacaoOut,
    ProdutoCreate,
    ProdutoEdit,
    ProdutoOut,
    RefreshRequest,
    RefreshResponse,
    SignupRequest,
    SignupResponse,
    TenantOut,
    TenantUpdate,
)
from cloud.schemas.v2_1 import (
    AdminStats,
    BrandingOut,
    BrandingPublic,
    BrandingUpdate,
    FaturaCreate,
    FaturaMarcarPago,
    FaturaOut,
    GoogleLoginRequest,
    GoogleSignupRequest,
    TenantAdminOut,
)

__all__ = [
    "AdminStats",
    "BrandingOut",
    "BrandingPublic",
    "BrandingUpdate",
    "FaturaCreate",
    "FaturaMarcarPago",
    "FaturaOut",
    "GoogleLoginRequest",
    "GoogleSignupRequest",
    "LoginRequest",
    "LoginResponse",
    "MovimentacaoIn",
    "MovimentacaoOut",
    "ProdutoCreate",
    "ProdutoEdit",
    "ProdutoOut",
    "RefreshRequest",
    "RefreshResponse",
    "SignupRequest",
    "SignupResponse",
    "TenantAdminOut",
    "TenantOut",
    "TenantUpdate",
]
